### ISSUE TITLE
BUG: gpu memory is not deallocated with Ctrl-C,Ctrl-z signal

### ISSUE THREAD

**Issue by nikitinvv** [math-vrn/libtike-cufft#16]
@carterbox, you said that 'with pt.CGPtychoSolver(nscan, nprb, ndetx, ndety, ntheta, nz, n, ptheta, igpu) as slv:...'  should handle ctrl-c, ctrl-z signals and deallocate memory. It doesn't work for me. Should we still use something like:
    def signal_handler(sig, frame):
        slv = []
        sys.exit(0)
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTSTP, signal_handler)

**Comment by carterbox** [comment]
I said that it should handle `CTRL-C` (`SIGINT`) only. The memory should not be deallocated with `CTRL-Z` because processes that are stopped may be resumed.

**Comment by nikitinvv** [comment]
oh, I see. thanks
