### ISSUE TITLE
Replace FFT interpolations with Bi-linear interpolation for speed

### ISSUE THREAD

**Issue by carterbox** [math-vrn/libtike-cufft#5]
@dgursoy requests that we use bi-linear interpolation because it is in theory faster O(4 * n^2) vs 2 * n^2 log(n^2).

**Comment by nikitinvv** [comment]
@dgursoy, @carterbox, It can also be done with cubic interpolation. But let's keep the natural interpolation (via FFT) for this development stage. It is surely slower, but this way we can control all the accuracy errors.
